### ISSUE TITLE
Demo or the trained model?

### ISSUE THREAD

**Issue by zobeirraisi** [simplify23/MRN#1]
Thanks for the fantastic work, Do you plan to release the demo code or the pre-trained models?

**Comment by simplify23** [comment]
All models can be trained using only two 3090 GPUs with appropriate configurations. We encourage users to directly train the corresponding models. However, due to the model sizes exceeding the limit of the free version of the cloud storage, we are unable to provide the respective training models temporarily (all experiments can be tried directly). If there are any difficulties, we will offer assistance. Additionally, for the task of incremental learning, we have not yet found an intuitive way to demonstrate it.
